# Generated by Django 4.2.2 on 2023-07-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='posts',
            new_name='news',
        ),
    ]
